package com.example.hello.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Setter;
import org.springframework.data.annotation.Id;
//import org.springframework.data.annotation.Id;

@Setter
@DynamoDBTable(tableName = "articles")
public class Article {

//    @DynamoDBRangeKey
    private String sk;
    private String author;
    private String content;
    private String type;
    private Integer score;

    @Id
    @JsonIgnore
    @DynamoDBIgnore
    private ArticleId articleId;

    public Article() {
        articleId = new ArticleId();
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getAuthor() {
        return author;
    }

    @DynamoDBRangeKey
    public String getSk() {
        return sk;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "content-index", attributeName = "content")
    public String getContent() {
        return content;
    }

    @DynamoDBAttribute
    public String getType() {
        return type;
    }

}
