package com.example.hello.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "dynamodb_demo")
@Data
public class Article {
    @Id
    ArticleId articleId;

    @DynamoDBAttribute(attributeName = "content")
    private String content;
    @DynamoDBAttribute(attributeName = "type")
    private String type;

    @DynamoDBIgnore
    public ArticleId getArticleId() {
        return articleId;
    }

    public Article() {
        articleId = new ArticleId();
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "pk")
    public String getAuthor() {
        return articleId != null ? articleId.getAuthor() : null;
    }

    public void setAuthor(String author) {
        if (articleId != null) {
            articleId.setAuthor(author);
        }
    }

    @DynamoDBRangeKey(attributeName = "sk")
    public String getSk() {
        return articleId != null ? articleId.getSk() : null;
    }

    public void setSk(String sk) {
        if (articleId != null) {
            articleId.setSk(sk);
        }
    }
}
