package com.example.hello.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.joda.time.DateTime;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName="dynamo_model_id")
public abstract class DynamoDBIdModel {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    protected String id;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.N)
    @DynamoDBAttribute
    protected DateTime lastUpdateTime;
}
